test_domains:
  - acevedo

output_dir: zoutput/benchmarks/BLOOD_acevedo_resnet_different_models_acevedo

# Number of hyperparameter samples per task.
num_param_samples: 5

startseed: 100
endseed: 101

domainlab_args:
  tpath: /home/aih/sina.wendrich/MA_thesis/tasks/task_blood2.py
  epos: 10
  es: 3
  npath: /home/aih/sina.wendrich/MA_thesis/nets/dinov2_nofreeze.py
  lr: 1e-5
  bs: 32

Shared_params:
  num_shared_param_samples: 5

  zx_dim:
    min: 0
    max: 96
    step: 32
    distribution: uniform
    datatype: int

  zy_dim:
    min: 32
    max: 96
    step: 32
    distribution: uniform
    datatype: int

  zd_dim:
    reference: zy_dim



erm:
  model: erm

diva:
  model: diva
  # set nname_dom = nname when changing nname
  npath_dom: /home/aih/sina.wendrich/MA_thesis/nets/dinov2_nofreeze.py
  shared:
    - zx_dim
    - zy_dim
    - zd_dim
  hyperparameters:
    gamma_d:
      min: 1e4
      max: 1e6
      step: 10_000
      distribution: loguniform
    gamma_y:
      min: 1e4
      max: 2e5
      step: 100
      distribution: loguniform

dann:
  model: dann
  trainer: hyperscheduler
  hyperparameters:
    gamma_reg:
      min: 0.001
      max: 0.1
      distribution: loguniform

irm:
  model: erm
  trainer: irm
  hyperparameters:
    gamma_reg:
      min: 0.001
      max: 0.1
      distribution: loguniform

dann_irm:
  model: dann
  trainer: irm
  hyperparameters:
    gamma_reg:
      min: 0.001
      max: 0.1
      distribution: loguniform



diva_irm:
  model: diva
  trainer: irm
  npath_dom: /home/aih/sina.wendrich/MA_thesis/nets/dinov2_nofreeze.py

  shared:
    - gamma_y
    - zx_dim
    - zy_dim
    - zd_dim
  hyperparameters:
    gamma_d:
      min: 1e4
      max: 1e6
      step: 10_000
      distribution: loguniform
    gamma_reg:
      min: 0.01
      max: 10
      distribution: loguniform
    gamma_y:
      min: 1e4
      max: 2e5
      step: 100
      distribution: loguniform

dial:
  model: erm
  trainer: dial
  hyperparameters:
    dial_steps_perturb:
      min: 1
      max: 1
      step: 1
      distribution: uniform
    dial_noise_scale:
      min: 0.0001
      max: 0.001
      distribution: loguniform
    dial_epsilon:
      min: 0.0001
      max: 0.001
      distribution: loguniform

dann_dial:
  model: dann
  trainer: dial
  hyperparameters:
    dial_steps_perturb:
      min: 1
      max: 1
      step: 1
      distribution: uniform
    dial_noise_scale:
      min: 0.0001
      max: 0.0001
      distribution: loguniform
    dial_epsilon:
      min: 0.001
      max: 0.001
      distribution: loguniform
    gamma_reg:
      min: 0.01
      max: 10
      distribution: loguniform

diva_dial:
  model: diva
  trainer: dial
  npath_dom: /home/aih/sina.wendrich/MA_thesis/nets/dinov2_nofreeze.py
  shared:
    - zx_dim
    - zy_dim
    - zd_dim
  hyperparameters:
    dial_steps_perturb:
      min: 1
      max: 1
      step: 1
      distribution: uniform
    dial_noise_scale:
      min: 0.0001
      max: 0.0001
      distribution: loguniform
    dial_epsilon:
      min: 0.001
      max: 0.001
      distribution: loguniform
    gamma_d:
      min: 1e4
      max: 1e6
      step: 10_000
      distribution: loguniform
    gamma_y:
      min: 1e4
      max: 2e5
      step: 100
      distribution: loguniform
