test_domains:
  - center0
  # - center1
  # - center2
  # - center3
  # - center4

output_dir: zoutput/benchmarks/CAMELYON_center0_wirklich_irm_lr1e5_bs16_classbalancing3

num_param_samples: 1

startseed: 100
endseed: 102

domainlab_args:
  tpath: /lustre/groups/aih/sina.wendrich/MA_code/MA_thesis/tasks/task_CAMELYON17.py
  bs: 16
  epos: 30
  es: 20
  lr: 1e-5

irm_resnet_config1:
  model: erm
  trainer: irm
  npath: /lustre/groups/aih/sina.wendrich/MA_code/MA_thesis/nets/resnet.py
  hyperparameters:
    gamma_reg:
      min: 0.0001
      max: 0.0001
      step: 0.1
      distribution: uniform

irm_resnet_config2:
  model: erm
  trainer: irm
  npath: /lustre/groups/aih/sina.wendrich/MA_code/MA_thesis/nets/resnet.py
  hyperparameters:
    gamma_reg:
      min: 0.001
      max: 0.001
      step: 0.1
      distribution: uniform

irm_resnet_config3:
  model: erm
  trainer: irm
  npath: /lustre/groups/aih/sina.wendrich/MA_code/MA_thesis/nets/resnet.py
  hyperparameters:
    gamma_reg:
      min: 0.01
      max: 0.01
      step: 0.1
      distribution: uniform

irm_resnet_config4:
  model: erm
  trainer: irm
  npath: /lustre/groups/aih/sina.wendrich/MA_code/MA_thesis/nets/resnet.py
  hyperparameters:
    gamma_reg:
      min: 0.1
      max: 0.1
      step: 0.1
      distribution: uniform

irm_resnet_config5:
  model: erm
  trainer: irm
  npath: /lustre/groups/aih/sina.wendrich/MA_code/MA_thesis/nets/resnet.py
  hyperparameters:
    gamma_reg:
      min: 1
      max: 1
      step: 0.1
      distribution: uniform
