

te_d: center4  # domain name of test domain
tpath: ../tasks/task_CAMELYON17.py  # python file path to specify the task
bs: 32  # batch size
es: 10
lr: 1e-4
model: dann  # model DANN
epos: 20  # number of epochs
gamma_reg: 0.001  # hyperparameter of DANN

npath: ../nets/vit.py  # neural network for class classification
npath_dom: ../nets/vit.py  # neural network for domain classification






