# List of all domains that are used as test domains
# In a leave-one-out setup, i.e., for each run,
# one domain from this list is chosen as test domain
# while training is performed on all other domains
# of the specified dataset.
test_domains:
  - center0

output_dir: ../zoutput/benchmarks/CAMELYON_centers_dann_dial

# Number of configurations per task.
# The total runs of each task are given
# by len(test_domains) * num_param_samples * num_seeds
num_param_samples: 1

san_check: True
san_num: 5

# Seeds for hyperparameter setting and experiments
# Ensures that the benchmark is reproducible.
startseed: 100
endseed: 100  # Start and end seeds are inclusive

domainlab_args:
  # Common settings passed to each task
  tpath: ../tasks/task_CAMELYON17.py
  bs: 32
  epos: 30
  es: 20
  lr: 1e-5

# Model configurations to be tested with fixed hyperparameters
erm_dinov2:
  model: erm
  npath: ../nets/dinov2.py

dann_dinov2_config1:
  model: dann
  npath: ../nets/dinov2.py
  hyperparameters:
    gamma_reg:
      min: 0.000001
      max: 0.000001
      step: 0.1

dann_dinov2_config2:
  model: dann
  npath: ../nets/dinov2.py
  hyperparameters:
    gamma_reg:
      min: 0.0001
      max: 0.0001
      step: 0.1

dial_dinov2_config1:
  model: erm
  trainer: dial
  npath: ../nets/dinov2.py
  hyperparameters:
    dial_steps_perturb:
      min: 1
      max: 1
    dial_noise_scale:
      min: 0.0001
      max: 0.0001
    dial_epsilon:
      min: 0.001
      max: 0.001

dial_dinov2_config2:
  model: erm
  trainer: dial
  npath: ../nets/dinov2.py
  hyperparameters:
    dial_steps_perturb:
      min: 3
      max: 3
    dial_noise_scale:
      min: 0.005
      max: 0.005
    dial_epsilon:
      min: 0.01
      max: 0.01

# Repeat the structured setup for other models with similar adjustments
erm_vit:
  model: erm
  npath: ../nets/vit.py

dann_vit_config1:
  model: dann
  npath: ../nets/vit.py
  hyperparameters:
    gamma_reg:
      min: 0.000001
      max: 0.000001
      step: 0.1

dann_vit_config2:
  model: dann
  npath: ../nets/vit.py
  hyperparameters:
    gamma_reg:
      min: 0.0001
      max: 0.0001
      step: 0.1

dial_vit_config1:
  model: erm
  trainer: dial
  npath: ../nets/vit.py
  hyperparameters:
    dial_steps_perturb:
      min: 1
      max: 1
    dial_noise_scale:
      min: 0.0001
      max: 0.0001
    dial_epsilon:
      min: 0.001
      max: 0.001

dial_vit_config2:
  model: erm
  trainer: dial
  npath: ../nets/vit.py
  hyperparameters:
    dial_steps_perturb:
      min: 3
      max: 3
    dial_noise_scale:
      min: 0.005
      max: 0.005
    dial_epsilon:
      min: 0.01
      max: 0.01

erm_resnet:
  model: erm
  npath: ../nets/resnet.py

dann_resnet_config1:
  model: dann
  npath: ../nets/resnet.py
  hyperparameters:
    gamma_reg:
      min: 0.000001
      max: 0.000001
      step: 0.1

dann_resnet_config2:
  model: dann
  npath: ../nets/resnet.py
  hyperparameters:
    gamma_reg:
      min: 0.0001
      max: 0.0001
      step: 0.1

dial_resnet_config1:
  model: erm
  trainer: dial
  npath: ../nets/resnet.py
  hyperparameters:
    dial_steps_perturb:
      min: 1
      max: 1
    dial_noise_scale:
      min: 0.0001
      max: 0.0001
    dial_epsilon:
      min: 0.001
      max: 0.001

dial_resnet_config2:
  model: erm
  trainer: dial
  npath: ../nets/resnet.py
  hyperparameters:
    dial_steps_perturb:
      min: 3
      max: 3
    dial_noise_scale:
      min: 0.005
      max: 0.005
    dial_epsilon:
      min: 0.01
      max: 0.01
